services:
  ros2:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        ROS_ENV: ${ROS_ENV}
        UID: ${UID}
        GID: ${GID}
    image: beluga_ros2
    tty: true         # Enable TTY allocation
    stdin_open: true  # Keep stdin open for interactive input
    user: "${UID}:${GID}"
    volumes:
      - /run/user/1000/wayland-0:/run/user/1000/wayland-0
      - /dev/dri:/dev/dri
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/wayland-sock
      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}
      - ./beluga_ws:/home/user/beluga_ws
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
