services:
  ros2:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        ROS_ENV: "jazzy"
        UID: ${UID}
        GID: ${GID}
    image: beluga_ros2
    tty: true         # Enable TTY allocation
    stdin_open: true  # Keep stdin open for interactive input
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    user: "${UID}:${GID}"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}
      - ./beluga_ws:/home/user/beluga_ws
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
