#!/bin/bash

source .utils/user.sh
source ros_config

UID_VAL=$(id -u)
GID_VAL=$(id -g)
DISPLAY_VAL="${DISPLAY:-:0}"

cat > .env <<EOF
# === Auto-generated by gen_env.sh ===
# === DO NOT EDIT DIRECTLY! ===

ROS_ENV=$ROS_ENV
ROS_TYPE=$ROS_TYPE

UID=$UID_VAL
GID=$GID_VAL
DISPLAY=$DISPLAY_VAL
EOF

if [ "$SESSION_TYPE" == "wayland" ]; then
    WAYLAND_DISPLAY_VAL="${WAYLAND_DISPLAY:-wayland-0}"
    XDG_RUNTIME_DIR_VAL="${XDG_RUNTIME_DIR:-/run/user/$UID_VAL}"
    cat >> .env <<EOF

# Wayland
QT_QPA_PLATFORM=wayland
WAYLAND_DISPLAY=$WAYLAND_DISPLAY_VAL
XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR_VAL
EOF

else
    XAUTHORITY_FILE="/tmp/.docker.xauth"
    cat >> .env <<EOF

# X11
XAUTHORITY=$XAUTHORITY_FILE
EOF
fi

D_PATH="docker/.env"
if [ -e "$D_PATH" ]; then
    TS=$(date +%Y%m%d-%H%M%S)
    mv "$D_PATH" "${D_PATH}.bak.${TS}"
fi

mv .env docker

echo ".env file generated..."